project_id = "nvoconkfclyboxzrqxyu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[storage]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325

[edge_functions]
enabled = true
port = 54326

[analytics]
enabled = false
port = 54327

[functions.scrape-product]
verify_jwt = true

[functions.ai-purchase-recommendation]
verify_jwt = false

[functions.search-platforms]
verify_jwt = false

[functions.google-shopping-search]
verify_jwt = false

[functions.daily-price-scraper]
verify_jwt = false