// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvoconkfclyboxzrqxyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52b2NvbmtmY2x5Ym94enJxeHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDQwMDgsImV4cCI6MjA2ODQ4MDAwOH0.BbRRv45is5E_wqNRYwUd1wOkj8oF0hy_wPzfZzQn38w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});